version: 2
jobs:
  build-push-docker:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t nexucis/ci-checkfiles:dev-master
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: docker push nexucis/ci-checkfiles:dev-master
  push-tag-docker:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: docker pull nexucis/ci-checkfiles:dev-master
      - run: docker tag nexucis/ci-checkfiles:dev-master nexucis/ci-checkfiles:${CIRCLE_TAG}
      - run: docker tag nexucis/ci-checkfiles:dev-master nexucis/ci-checkfiles:latest
      - run: docker push nexucis/ci-checkfiles:${CIRCLE_TAG}
      - run: docker push nexucis/ci-checkfiles:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-push-docker:
          filters:
            branches:
              only:
                - master
      - push-tag-docker:
          type: approval
          filters:
            tags:
              only: /.*/